import Link from "next/link"
import './globals.css'
import { Control } from "./Control";

export const metadata = {
  title: 'Hyerin\'s Next App',
  description: 'Generated by hyerin',
}

export default async function RootLayout({ children }) {
  // const resp = await fetch('http://localhost:8000/topics', { next: { revalidate: 0 } }); // 숫자 동안만 캐시 유지, 숫자(초)가 지나면 그 캐시는 다시 만들어진다.
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', { cache: 'no-store' });       // 캐시 정책을 저장하지 않는다.
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
