"use client";
import Link from "next/link"
import './globals.css'
import { useEffect, useState } from "react"

// export const metadata = {
//   title: 'Hyerin\'s Next App',
//   description: 'Generated by hyerin',
// }

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);

  // 서버에서 클라이언트로 데이터를 땡겨오기 위해 useEffect()
  useEffect(() => {
    fetch('http://localhost:8000/topics')
      .then(resp => {
        return resp.json();
      })
      .then(result => {
        setTopics(result);
      });
  }, [])
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  )
}
